language: java
dist: trusty
jdk:
  - oraclejdk8
  
after_success:
  - mvn clean test jacoco:report coveralls:report # report coverage to coveralls
  
# use latest java version available instead of travis default
addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false # route the build to the container-based infrastructure for a faster build

notifications:
  email:
    - iluwatar@gmail.com
